name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject environment variables
        run: |
          echo "window.EMAILJS_USER_ID='${{ secrets.EMAILJS_USER_ID }}';" > ./env.js
          echo "window.EMAILJS_SERVICE_ID='${{ secrets.EMAILJS_SERVICE_ID }}';" >> ./env.js
          echo "window.EMAILJS_TEMPLATE_ID='${{ secrets.EMAILJS_TEMPLATE_ID }}';" >> ./env.js

      - name: Add and commit env.js
        run: |
          git config --global user.email "aurelien.lehyaric@live.com"
          git config --global user.name "AurelienLeHyaric"
          git add env.js
          git commit -m "Add env.js with environment variables"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
